<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>ScreenTranslator</AssemblyName>
    <RootNamespace>ScreenTranslator</RootNamespace>
    <Version>1.0.0</Version>

    <!-- Чёткий рендер на любых мониторах -->
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>

    <!-- Скорость и размер -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <TieredPGO>true</TieredPGO>
    <TieredCompilationQuickJitForLoops>true</TieredCompilationQuickJitForLoops>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
